source 'https://github.com/CocoaPods/Specs.git'

xcodeproj '../../ByApartments'
workspace '../../ByApartments'
platform :ios, '7.0'
inhibit_all_warnings!
#use_frameworks!

pod 'Parse'
pod 'ParseUI'
pod 'PromiseKit', '~> 1.5'
pod 'Parse+PromiseKit', '~> 0.9.2'
pod 'SDWebImage'
pod 'MMDrawerController', '~> 0.6.0'
pod 'TTRangeSlider'
pod 'Masonry'
#pod 'NSLogger'