source 'https://github.com/CocoaPods/Specs.git'

xcodeproj '../../ByApartments'
workspace '../../ByApartments'
platform :ios, '7.0'
inhibit_all_warnings!

pod 'Parse'
pod 'ParseUI'
pod 'PromiseKit'
pod 'Parse+PromiseKit', '~> 0.9.2'
pod 'SDWebImage'
#pod 'NSLogger'
